import { Navigation } from '@/components';
import './globals.css';

export const metadata = {
  title: 'QuantMaster',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='zh_CN'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
