import { Inter } from 'next/font/google';
import { Navigation } from '@/components';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'QuantMaster',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh_CN">
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
